create table if not exists public.profiles (
  public_id text primary key,
  edit_token_hash text not null,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.waitlist_entries (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null unique,
  source text not null default 'landing',
  created_at timestamptz not null default now()
);

create table if not exists public.profile_views (
  id bigint generated by default as identity primary key,
  public_id text not null references public.profiles(public_id) on delete cascade,
  session_id text not null,
  referrer text,
  user_agent text,
  viewed_at timestamptz not null default now(),
  unique (public_id, session_id)
);

create index if not exists profile_views_public_id_viewed_at_idx
  on public.profile_views (public_id, viewed_at desc);

create table if not exists public.profile_clicks (
  id bigint generated by default as identity primary key,
  public_id text not null references public.profiles(public_id) on delete cascade,
  session_id text not null,
  event_id text not null,
  link_id text not null,
  link_type text not null check (link_type in ('link', 'product')),
  link_title text not null,
  target_url text not null,
  user_agent text,
  clicked_at timestamptz not null default now(),
  unique (public_id, event_id)
);

create index if not exists profile_clicks_public_id_clicked_at_idx
  on public.profile_clicks (public_id, clicked_at desc);

create index if not exists profile_clicks_public_id_link_id_idx
  on public.profile_clicks (public_id, link_id);

alter table public.profiles enable row level security;
alter table public.waitlist_entries enable row level security;
alter table public.profile_views enable row level security;
alter table public.profile_clicks enable row level security;

-- All table access goes through server-side route handlers using the
-- service-role key, so no browser-facing RLS policy is required.
